# Generated by Django 4.2.13 on 2024-08-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publication',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
