# Generated by Django 4.2.13 on 2024-08-13 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product_name',), 'permissions': [('can_cancel_publication', 'can cancel publication of product'), ('can_change_description', 'cab change description of product'), ('can_change_product_category', 'cab change category of product')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
